# Generated by Django 5.2.15 on 2026-06-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='symbol',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
