# Generated by Django 5.2.15 on 2026-06-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_election_school_slug_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='symbol_name',
            field=models.CharField(blank=True, help_text="Text to display alongside the symbol (e.g. 'Globe')", max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='candidates/photos'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='symbol',
            field=models.ImageField(blank=True, null=True, upload_to='candidates/symbols'),
        ),
    ]
