# Generated by Django 5.2.3 on 2026-06-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_candidate_symbol_name_alter_candidate_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='school_name',
            field=models.CharField(blank=True, help_text='The school this invigilator is assigned to (blank for superusers/all schools).', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school_slug',
            field=models.SlugField(blank=True, help_text='The school slug this invigilator is assigned to.', max_length=100),
        ),
    ]
