# Generated by Django 5.2.3 on 2026-06-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_userprofile_school_name_userprofile_school_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='exclude_votes',
            field=models.BooleanField(default=False, help_text='Exclude votes cast during sessions started by this invigilator from final results counting.'),
        ),
    ]
