# Generated by Django 5.2.15 on 2026-06-27 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_userprofile_exclude_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id_hash', models.CharField(db_index=True, max_length=64)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_registrations', to='voting.election')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('election', 'student_id_hash'), name='uniq_voter_registration_per_election')],
            },
        ),
    ]
