# Generated by Django 5.2.15 on 2026-06-27 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_kioskpresence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiosk_id', models.CharField(db_index=True, max_length=64)),
                ('student_id_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('done', 'Done'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_kiosk_sessions', to=settings.AUTH_USER_MODEL)),
                ('ballot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kiosk_session', to='voting.ballot')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kiosk_sessions', to='voting.election')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
