# Generated by Django 5.2.15 on 2026-07-02 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_kiosksession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('student_class', models.CharField(help_text='e.g. 10, 11, 12', max_length=20)),
                ('division', models.CharField(blank=True, help_text='e.g. A, B, C', max_length=10)),
                ('student_id', models.CharField(blank=True, help_text='Admission/Roll number used to uniquely identify the student for voting.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='voting.election')),
            ],
            options={
                'ordering': ('student_class', 'division', 'name'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('student_id__gt', '')), fields=('election', 'student_id'), name='uniq_student_id_per_election')],
            },
        ),
    ]
