# Generated by Django 5.2.15 on 2026-07-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0012_add_student_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='manual_override_password_hash',
            field=models.CharField(blank=True, help_text='Hashed password used for kiosk manual override at this school.', max_length=256),
        ),
    ]
