# Generated by Django 5.2.15 on 2026-07-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0013_election_manual_override_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='manual_override_password_plain',
            field=models.CharField(blank=True, help_text='Plain text password used for kiosk manual override at this school.', max_length=256),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plain_password',
            field=models.CharField(blank=True, help_text='Plain text password of the invigilator account.', max_length=256),
        ),
    ]
