# Generated by Django 5.2.15 on 2026-07-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0014_election_manual_override_password_plain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('invigilator', 'Invigilator'), ('teacher', 'Teacher')], default='invigilator', help_text='The role of this user (invigilator or teacher).', max_length=20),
        ),
    ]
