# Generated by Django 5.2.15 on 2026-07-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0015_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('invigilator', 'Invigilator'), ('teacher', 'Teacher'), ('kiosk', 'Kiosk')], default='invigilator', help_text='The role of this user (invigilator, teacher, or kiosk).', max_length=20),
        ),
    ]
