# Generated by Django 5.2.15 on 2026-07-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0016_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_device_id',
            field=models.CharField(blank=True, help_text='Tracks the unique active device ID for this kiosk/user to prevent concurrent sessions.', max_length=64),
        ),
    ]
