# Generated by Django 5.2.15 on 2026-07-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0017_userprofile_current_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='kiosk_timeout',
            field=models.PositiveIntegerField(default=90, help_text='Kiosk timeout in seconds for voting sessions.'),
        ),
    ]
